install:
	-sudo cp edlab-filemanager /usr/local/bin

examples:
	touch file-1.txt
	touch file-01.txt
	touch file-001.txt
	touch file-4.txt
	touch file-145.txt
	touch file-10.txt
	touch abacaxi-10.txt

clean:
	rm *.txt
