mv coversab coversab.csv
mv coversac coversac.csv
mv coversad coversad.csv
mv coversae coversae.csv
mv coversaf coversaf.csv
mv coversag coversag.csv
mv coversah coversah.csv
mv coversai coversai.csv
mv coversaj coversaj.csv
mv coversak coversak.csv
mv coversal coversal.csv
mv coversam coversam.csv
mv coversan coversan.csv
mv coversao coversao.csv
mv coversap coversap.csv
mv coversaq coversaq.csv
mv coversar coversar.csv
mv coversas coversas.csv
mv coversat coversat.csv
mv coversau coversau.csv
mv coversav coversav.csv
mv coversaw coversaw.csv
mv coversax coversax.csv
mv coversay coversay.csv
mv coversaz coversaz.csv
mv coversba coversba.csv
mv coversbb coversbb.csv
mv coversbc coversbc.csv
mv coversbd coversbd.csv
mv coversbe coversbe.csv
mv coversbf coversbf.csv
mv coversbg coversbg.csv
mv coversbh coversbh.csv
mv coversbi coversbi.csv
mv coversbj coversbj.csv
mv coversbk coversbk.csv
mv coversbl coversbl.csv
mv coversbm coversbm.csv
mv coversbn coversbn.csv
mv coversbo coversbo.csv
mv coversbp coversbp.csv
mv coversbq coversbq.csv
mv coversbr coversbr.csv
mv coversbs coversbs.csv
mv coversbt coversbt.csv
mv coversbu coversbu.csv
mv coversbv coversbv.csv
mv coversbw coversbw.csv
mv coversbx coversbx.csv
mv coversby coversby.csv
mv coversbz coversbz.csv
mv coversca coversca.csv
mv coverscb coverscb.csv
mv coverscc coverscc.csv
mv coverscd coverscd.csv
mv coversce coversce.csv
mv coverscf coverscf.csv
mv coverscg coverscg.csv
mv coversch coversch.csv
mv coversci coversci.csv
mv coverscj coverscj.csv